---
- name: Satellite server configuration playbook
  hosts: satellite
  become: true
  vars_prompt:
    - name: rhsm_user
      prompt: What is your RHSM Username (RHNID)?
      unsafe: yes
      private: no

    - name: rhsm_password
      prompt: What is your RHSM Password?
      unsafe: yes
      private: yes

    - name: rhsm_pool_id
      prompt: What is the pool-id for your subscription (check README)?
      unsafe: yes
      private: no

  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"

    - name: Disable all RHSM repositories
      community.general.rhsm_repository:
        name: '*'
        state: disabled
        
    - name: Enable required RHSM repositories
      community.general.rhsm_repository:
        name: 
          - rhel-7-server-rpms
          - rhel-7-server-satellite-6.10-rpms
          - rhel-7-server-satellite-maintenance-6-rpms
          - rhel-server-rhscl-7-rpms
          - rhel-7-server-ansible-2.9-rpms
        state: enabled

    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest

    - name: Install satellite packages
      yum:
        name: 
          - satellite
          - chrony
        state: latest

    - name: Ensure chrony is enabled
      service:
        name: chronyd
        enabled: true
        state: started

    - name: Ensure firewalld is enabled
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow ports for satellite zone
      ansible.posix.firewalld:
        zone: public
        state: enabled
        permanent: yes
        port: "{{ item }}"
      loop: 
        - 80/tcp
        - 443/tcp
        - 5647/tcp
        - 8000/tcp
        - 8140/tcp 
        - 9090/tcp
        - 53/udp
        - 53/tcp
        - 67/udp
        - 69/udp

    - name: Reload firewalld service
      service:
        name: firewalld
        state: restarted


    - name: Install satellite
      shell: | 
        satellite-installer --scenario satellite \
        --foreman-initial-organization "Red Hat" \
        --foreman-initial-location "Raleigh" \
        --foreman-initial-admin-username admin \
        --foreman-initial-admin-password redhat

    - name: Reboot server
      reboot: 