- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: true
  collections:
    - freeipa.ansible_freeipa
  roles:
  - role: freeipa.ansible_freeipa.ipaclient
    state: present
