---
- name: Satellite server configuration playbook
  hosts: satellite
  become: true
  vars_prompt:
    - name: rhsm_user
      prompt: What is your RHSM Username (RHNID)?
      unsafe: yes
      private: no

    - name: rhsm_password
      prompt: What is your RHSM Password?
      unsafe: yes
      private: yes

    - name: rhsm_pool_id
      prompt: What is the pool-id for your subscription (check README)?
      unsafe: yes
      private: no

  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"

    - name: Disable all RHSM repositories
      community.general.rhsm_repository:
        name: '*'
        state: disabled
        
    - name: Enable required RHSM repositories
      community.general.rhsm_repository:
        name: 
          - jb-eap-7.4-for-rhel-8-x86_64-rpms
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - rh-sso-7.5-for-rhel-8-x86_64-rpms
        state: enabled

    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest

    - name: Install SSO packages
      yum:
        name: '@rh-sso7'
        state: latest

    - name: Ensure chrony is enabled
      service:
        name: chronyd
        enabled: true
        state: started

    - name: Ensure firewalld is enabled
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow ports for SSO
      ansible.posix.firewalld:
        zone: public
        state: enabled
        permanent: yes
        port: "{{ item }}"
      loop: 
        - 8080/tcp
        - 8443/tcp
        - 9990/tcp
        - 9993/tcp
        - 443/tcp 
        - 389/tcp
        - 636/udp

    - name: Reload firewalld service
      service:
        name: firewalld
        state: restarted

    - name: Reboot server
      reboot: 